name: places
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.5"

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  drift: 2.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.1
  geolocator: ^9.0.1
  http_parser: ^4.0.2
  image_picker: ^0.8.7+3
  mime_type: ^1.0.0
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  provider: ^6.0.3
  shared_preferences: ^2.0.18
  smooth_page_indicator: ^1.0.0+2
  sqlite3_flutter_libs: ^0.5.13
  surf_lint_rules: ^1.5.0
  yandex_mapkit: ^3.2.0

dependency_overrides:
  geolocator: 9.0.1
  geolocator_android: 4.1.4

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: 2.2.0+1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/ui/res/icons/
    - lib/ui/res/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/ui/res/fonts/Roboto-Bold.ttf
        - asset: lib/ui/res/fonts/Roboto-Regular.ttf
