name: places
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  surf_lint_rules: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - lib/ui/res/icons/
    - lib/ui/res/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/ui/res/fonts/Roboto-Bold.ttf
        - asset: lib/ui/res/fonts/Roboto-Regular.ttf

    