name: places
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.5"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^1.0.3
  geolocator: ^9.0.1
  mobx: ^2.1.3
  provider: ^6.0.3
  smooth_page_indicator: ^1.0.0+2
  surf_lint_rules: ^1.5.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1

flutter:

  uses-material-design: true

  assets:
    - lib/ui/res/icons/
    - lib/ui/res/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/ui/res/fonts/Roboto-Bold.ttf
        - asset: lib/ui/res/fonts/Roboto-Regular.ttf
